### PR TITLE
Py3 devel

### PR DESCRIPTION
**Pull request by jeffkinnison**
This is the updated version of AWE-WQ compatible with Python 3. The change was originally made to eliminate a memory leak caused by the Python 2 runtime's memory management strategy, but in the process some superfluous network and disk I/O was also eliminated.

### CODE REVIEW

**Comment by badmutex** [comment]
Thanks for this work Jeff.
I glanced at the changed and have a few questions.

Did you intend to add the contents of the `2to3` directory?
For instance, should `2to3/awe/_diff_aweclasses.txt` be under source control?

Could you describe a bit the Python 2 memory management issue? What other references are there for this? What are the other network/disk issues that were fixed?

Does this introduce a requirement on Python 3 or can it still be run under Python 2 (with the caveat that Python 2 has the memory issue)?

**Comment by jeffkinnison** [comment]
The 2to3 directory is just an archive of the changes I made to update from version 2 to 3, in case we need to roll back. It probably doesn't need to be in the repo, though.

The Python 2 memory management issue was a known issue with Python 2's usage of glibc that caused the Python runtime to think memory was being released, when in actuality is was never returned to the OS. The memory model was essentially using a stack and could only free memory from the top of the stack. However, if you create many new objects before releasing old ones (for example, updating Walker positions using numpy arrays), this would add more to the top of the stack, preventing the old ones from being released. This wouldn't show up in Python-internal memory profiling because all of the references to the old objects are gone, so Python thinks it has done its job.

That issue really only showed up on longer runs of AWE, and I only found it because reported memory consumption from the OS and Python were radically different. In Python 3.3, this issue was finally fixed because Python's internal memory management model was restructured.

The I/O was not a an issue, but an optimization--I removed the pickled Walker objects from the software logic. Python 3 uses a nonstandard encoding for pickle strings, and the WorkQueue C bindings couldn't understand that encoding. My original fix was to write the pickled Walkers to file and send those files to the Workers, but as you can imagine this caused a lot of extra disk I/O. The current software just uses task tags to capture all of the information necessary to associate a simulation result with the appropriate Walker. By not sending the pickled Walker object with each task, there's the added bonus of reducing network I/O.

I haven't done extensive testing with Python 2, but I tried to make the resulting code 2- and 3-compatible. Python 3.4 and up is definitely recommended, though, especially for long jobs, because the memory management issue was internal to Python 2.x and 3.0-3.3.

**Comment by dthain** [comment]
@jeffkinnison you know the code best at this point, so it's up to you to consider Badi's input and then merge when it is ready.  We want to get back to using this repo as the steady state.

**Comment by jeffkinnison** [comment]
I've been using this successfully for quite some time now, so I'm going to go ahead and say we merge. It doesn't look like I have write access to this repo, though, so I can't actually do the merge.

**Comment by dthain** [comment]
Hmm, I think you have a pending invitation to write access.  Double check your email, or perhaps you can see if from your github profile.

**Pull request merged**
